### ISSUE TITLE
Upcoming breaking api changes

### ISSUE THREAD

**Issue by hakuseki** [daskeyboard/daskeyboard-applet--weather-international#1]
Output shows no weather but instead a message:

_NB! Read the comments in the apiChanges section in the XML_

```
<!--NB!!! Since we have no other options to contact our users of forecast.xml, we have decided to use this method to get your attention to some major changes with our API-->
    <!--In the first quarter next year, forecast.xml and forecast_hour_by_hour.xml will be discontinued in favour of a newer JSON API.-->
    <!--Vi encourage you already now to switch to the new API.-->
    <!--There are a lot of changes, and you can read all the technical details in our new developer portal https://developer.yr.no-->

```

![Q_Signal_Center_-_Das_Keyboard](https://user-images.githubusercontent.com/5478862/91860157-9c877400-ec6b-11ea-9f7d-20edb58d80ba.png)

**Comment by fabiendv** [comment]
I am not able to reproduce the issue.
Can you tell more about your configuration (city and unit type)?

**Comment by hakuseki** [comment]
Well if this hasn't been implemented it is self-fixed cause I have no issues anymore.
