### ISSUE TITLE
Cannot read property 'forecast' of undefined

### ISSUE THREAD

**Issue by hakuseki** [daskeyboard/daskeyboard-applet--weather-international#8]
Running on my Windows machine using Stockholm, Stockholm (Sweden).

Applet is not working properly, returns with the following error message:

```
The Weather forecast International service returned an error. Detail: TypeError: Cannot read property 'forecast' of undefined
```

**Comment by fabiendv** [comment]
Thanks for reporting this.

The new version will fix this issue.
